// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bukkgajsxankjjpnpljt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1a2tnYWpzeGFua2pqcG5wbGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTE1MDMsImV4cCI6MjA2MTAyNzUwM30.ha6Fr_uMBAEbUPOloPgaeOyW1VXI4U9GNWQ8zh4N-XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);